### ISSUE TITLE
Add robust Error handling method to check for errors while installing thirdparty modules using pip.

### ISSUE THREAD

**Issue by Anish-M-code** [gowtham758550/password-generator-and-manager#10]
Using Traditional ping method to check for internet connectivity to avoid errors due to low internet connectivity is slow. we are currently exploring a fix to this bug , currently the pip checks for such issues and reports errors.

**Comment by gowtham758550** [comment]
Now the code will return error if there is no internet connection. So I am going add some changes with request module to check internet connectivity

**Comment by Anish-M-code** [comment]
we can't use request module because we have to install it using pip. urllib may be an alternative if it isn't complex.

**Comment by gowtham758550** [comment]
So I found alternate module urllib and it requires no installation. Now I made some changes in the code. I works well :)
