### ISSUE TITLE
Issue in files

### ISSUE THREAD

**Issue by Raagul26** [gowtham758550/password-generator-and-manager#14]
If u generate more than one website name and password without exiting the program, it overwriting the previously generate website name and password. And also password count increases
ie. If your first password length is 10 , then if u create another password for another website with password length of 5 but it creates for 15(10+5).

**Comment by gowtham758550** [comment]
Yes da not only those errors. I found so many bugs 😭 I am working on it.

**Comment by Anish-M-code** [comment]
we will develop a patch soon thanks for reporting

**Comment by gowtham758550** [comment]
Now we can generate multiple passwords but unable fetch those passwords and I am trying to clear that bug

**Comment by gowtham758550** [comment]
I found the bug it's bcoz the code is search for passwords in a wrong file😂. Now I fix it
