### ISSUE TITLE
Program Crashes if confirm password is different than First password during First run

### ISSUE THREAD

**Issue by Anish-M-code** [gowtham758550/password-generator-and-manager#15]
![VirtualBox_Dev_30_05_2020_21_55_49](https://user-images.githubusercontent.com/58029804/83334224-9d9eb300-a2c2-11ea-9494-2654058e3bba.png)

To reproduce the bug. Do Fresh installation of program. Enter password to create master password ( i entered sad ) and type different password in confirm password ( i typed bad ) and program crashed!
This is a severe bug. We must patch it soon. ;(

**Comment by Anish-M-code** [comment]
This bug seems to affect version 0.0.4.1 and we can assume previous versions are also affected!!!

**Comment by gowtham758550** [comment]
Now I made a condition to check if the two inputs are same
