### ISSUE TITLE
Password Manager Crashes if user attempts to fetch password without creating any user passwords.

### ISSUE THREAD

**Issue by Anish-M-code** [gowtham758550/password-generator-and-manager#17]
![critical bug](https://user-images.githubusercontent.com/58029804/83335346-ce361b00-a2c9-11ea-975e-499c7aa1d350.png)

After first run of the program if user doesnot create any user password and directly tries to fetch password. The password manager crashes.

This bug seems to affect version 0.0.4.1 and we can assume previous versions are also affected!!!

**Comment by gowtham758550** [comment]
Now the check that user already create a password or not
