### ISSUE TITLE
Critical Bug: Fetching user passwords doesnot work in version 0.0.5

### ISSUE THREAD

**Issue by Anish-M-code** [gowtham758550/password-generator-and-manager#22]
The user password is cannot be fetched  and throws no password generated even if a password was generated by user. ;(

**Comment by Anish-M-code** [comment]
This bug still exists . after we close the password manager and try to fetch user password.

**Comment by Anish-M-code** [comment]
By analysing line 168 to line 211 i found that our password manager never wrote the generated 
user password for later use. instead it is just stored as global variable in our program and disappears as soon as we close the program.

**Comment by Anish-M-code** [comment]
![eternalbug](https://user-images.githubusercontent.com/58029804/84509476-61674b80-ace1-11ea-96af-732e96e15aed.png)
Seems it is a very huge bug to clean up ;(

**Comment by gowtham758550** [comment]
Now those problems are solved. And this problem is a simple logical 😂 error while returning the password while calling the function to fetch the password.

**Comment by gowtham758550** [comment]
Now this issue is solved. And this is just a simple logical error 😂 while returning the password.
