### ISSUE TITLE
Update Password cracking tool for latest 2.0 version

### ISSUE THREAD

**Issue by Anish-M-code** [gowtham758550/password-generator-and-manager#25]
The current password recovery tool doesnot work and we have to create a password cracking tool to crack passwords even though this can be extremly difficult .

**Comment by gowtham758550** [comment]
that's in your hand 😁

**Comment by Anish-M-code** [comment]
i have decided to keep old version as it works well against our GUI version of password manager.

i will update readme👍

**Comment by Anish-M-code** [comment]
Regarding version 2.0 recovery wont be guranteed as we have to crack password no known backdoors exist. so  i have decided to create new recovery tool from scratch.

**Comment by Anish-M-code** [comment]
I have decided that there is no use in creating password recovery tool and it is not worth the limited time i have. ;(

**Comment by Anish-M-code** [comment]
i think it will be still better to create Password recovery tool. [ status: confirmed ]
i will assign myself for this task. Anyway the old recovery tool still works on gui version .
