### ISSUE TITLE
Decide on migrating away from Pyaescrypt .

### ISSUE THREAD

**Issue by Anish-M-code** [gowtham758550/password-generator-and-manager#27]
Currently we use Pyaescrypt module which is a 3rd party module. should we stick with it or try cryptography module instead?

**Comment by gowtham758550** [comment]
🤔

**Comment by Anish-M-code** [comment]
We can stick with it. cryptography module is too complex and we can make mistakes

**Comment by Anish-M-code** [comment]
Is there any plan to transition to cryptography module at some point?
or should we stick to pyaescrypt?

**Comment by gowtham758550** [comment]
It's under development.

**Comment by Anish-M-code** [comment]
the bugs in the development version were too terrible to include in our main code and i don't think it will be worth our time to migrate so sticking back to pyaescrypt .
