### ISSUE TITLE
Code Audit

### ISSUE THREAD

**Issue by Anish-M-code** [gowtham758550/password-generator-and-manager#30]
Currently i think our software needs lots of testing and i am trying hard to report issues.
We need someone to audit code to remove unnecessary lines of code and reduce amount of code.
Third party audits are better.

Assigning task to Gowtham.

**Comment by gowtham758550** [comment]
1st audit status 200
@[Godwin](https://github.com/GodwinUjeen)  make a look at our code and says it's so good
