### ISSUE TITLE
After changing Master Password User Passwords get corrupted or lost.

### ISSUE THREAD

**Issue by Anish-M-code** [gowtham758550/password-generator-and-manager#31]
currently after adding feature to change master password  the code changes mp.text by decrypting it and re-encrypting with new key to display changes but forgot to decrypt and re-encrypt secret.txt which has user passwords with new key, causing data corruption and loss of user passwords.

This issue is very severe and should be patched as soon as possible.

**Comment by gowtham758550** [comment]
Review the pull request and merge asap.

**Comment by Anish-M-code** [comment]
ok done
