### ISSUE TITLE
Critical Issues

### ISSUE THREAD

**Issue by Raagul26** [gowtham758550/password-generator-and-manager#34]
There is a big hole in this program.  If you delete mp.txt.aes file and create new password, your generated and managed passwords can be retrieved.
 Fix it asap.

**Comment by gowtham758550** [comment]
If you do like that you cannot retrieve password and all the files are encrypted with that old password. If you try to fetch password file will not decrypted back with that new password.

**Comment by Raagul26** [comment]
No, i retrieved all passwords generated with old password after deleting and creating new password.
plz check that

**Comment by Anish-M-code** [comment]
security bug confirmed we are working to fix it. It affects all platforms.

**Comment by Anish-M-code** [comment]
This issue is now fixed
