### ISSUE TITLE
Request to add Field to enter website and open trusted website using password manager to avoid phishing.

### ISSUE THREAD

**Issue by evil-user** [gowtham758550/password-generator-and-manager#42]
**Is your feature request related to a problem? Please describe.**
Avoids phishing attacks

**Describe the solution you'd like**
store an additional field in database and load website when needed.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by Anish-M-code** [comment]
It is partially implemented within this password manager , we devs are very busy people and this is just a hobby project developed for fun.

Due to lack of time and developer resources closing this.
